code/proj/urls.py
from .urls_base import *

urlpatterns = urlpatterns + [
    path('', include('suppliers.urls')),
]

code/switchblade_users/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.utils.translation import gettext as _

from switchblade_dashboard.forms import FormSetHelper

from switchblade_dashboard.decorators import register_resource
from switchblade_dashboard.views import DashboardIndexView
from .apis import UserUpdateAvatarAPI
from .autocomplete import UserAutocomplete, UserResourceAutocomplete, RoleAutocomplete
from .views import UserNotification, UserListView, UserCreateView, UserDetailView, \
    UserUpdateView, UserDeleteView, UserUpdateAvatarView, RoleList, RoleCreate, RoleDetail, \
    RoleUpdate, RoleDelete, UserChangePassword, UserProfileChangeView

urlpatterns = [

    path('auth/', include([
        path('login/', auth_views.LoginView.as_view(template_name='auth/login.html', redirect_authenticated_user=True),
             name='login'),
        path('logout/', auth_views.LogoutView.as_view(), name='logout'),

        path('reset-password/', auth_views.PasswordResetView.as_view(template_name='auth/password_reset.html',
                                                                     extra_context={'helper': FormSetHelper}),
             name='password_reset'),

        path('reset-password-done/', auth_views.PasswordResetDoneView.as_view(template_name='auth/password_reset_done.html'),
             name='password_reset_done'),

        path('reset-password-confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
            template_name='auth/password_reset_confirm.html',
            extra_context={'helper': FormSetHelper}),
            name='password_reset_confirm'),

        path('reset-password-complete/', auth_views.PasswordResetCompleteView.as_view(
            template_name='auth/password_reset_complete.html'),
            name='password_reset_complete'),

        path('notifications', login_required(UserNotification.as_view()), name='user-notifications'),
        path('autocomplete/', login_required(UserAutocomplete.as_view()), name='user-autocomplete'),
    ])),

    path('profile/', include([
        path('', register_resource(
            DashboardIndexView.as_view(page_title='Profile', header='Profile', columns=[3, 3, 3, 3])),
             name='dashboard-profile'),
        path('personal-info/', register_resource(UserProfileChangeView), name='profile-personal-info'),
        path('avatar/', register_resource(UserUpdateAvatarView), name='profile-avatar-update'),
        path('change-password/', auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('profile-password-done'), template_name='auth/password_change.html',
                                                                       extra_context={'helper': FormSetHelper, 'PageTitle': _('Change Password')}),

             name='profile-password-change'),
        path('change-password-done/',
             auth_views.PasswordChangeDoneView.as_view(template_name='auth/password_change_done.html'),
             name='profile-password-done'),
    ])),


    path('config/', include([
        path('change-password/', login_required(UserChangePassword.as_view()), name='users-change-password'),

        path('users/', include([
            path('', register_resource(UserListView), name='users-list'),
            path('create/', register_resource(UserCreateView), name='users-create'),
            path('detail/<int:pk>', register_resource(UserDetailView), name='users-detail'),
            path('update/<int:pk>', register_resource(UserUpdateView), name='users-update'),
            path('delete/<int:pk>', register_resource(UserDeleteView), name='users-delete'),
        ])),

        path('roles/', include([
            path('', register_resource(RoleList), name='users-role-list'),
            path('create/', register_resource(RoleCreate), name='users-role-create'),
            path('detail/<int:pk>', register_resource(RoleDetail), name='users-role-detail'),
            path('update/<int:pk>', register_resource(RoleUpdate.as_view(), as_view=False, resource='role.update',description="Update Roles"), name='users-role-update'),
            path('delete/<int:pk>', register_resource(RoleDelete), name='users-role-delete'),
            path('autocomplete/', login_required(RoleAutocomplete.as_view()), name='role-autocomplete'),
            path('resources/autocomplete/', login_required(UserResourceAutocomplete.as_view()),
                 name='userresource-autocomplete'),
        ])),

    ])),


    path('api/', include([
        path('users/avatar/update/', UserUpdateAvatarAPI.as_view(), name='api-users-avatar-update'),
    ])),
]

code/switchblade_users/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.templatetags.static import static
from django.db import models
from django.db.models import Q, Value
from django.db.models.functions import Concat
from django.urls import reverse
from django.utils.functional import cached_property
from django.utils.translation import ugettext_lazy as _


class UserManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, password):
        user = self.create_user(
            email,
            first_name,
            last_name
        )
        user.set_password(password)
        user.is_admin = True
        user.is_staff = True
        self.save = user.save(using=self._db)
        return user


class UserResource(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    menu_type = models.BooleanField(default=False)
    order = models.IntegerField(default=0)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return f'{self.name} ({self.description})'

    @classmethod
    def get_resource_tree(cls, selected_ids=[], custom_root_parent=[]):

        base_qs = cls.objects.filter(menu_type=False).order_by('order', 'name')

        def get_children(node, parent_id, parent_ids=[]):

            children = base_qs.filter(name__regex=r'(^{}\.[^*][\w]*$)|(^{}\.[^*][\w]*\.\*)'.format(node, node))

            return_list = []

            for child in children:
                item = {
                    'id': child.id,
                    'name': child.name,
                    'description': child.description,
                    'selected': True if child.id in selected_ids else False,
                    'children': [],
                    'parents': parent_ids + [parent_id] + custom_root_parent
                }

                if child.name.split('.')[-1] == '*':
                    item['children'] = get_children(child.name.replace('.*', ''), child.id, item['parents'])

                return_list.append(item)

            return return_list

        results = []
        support_list = []
        leafs = {}

        roots = base_qs.filter(name__regex=r'^[^.]*\.\*')

        for root in roots:

            root_name = root.name.replace('.*', '')

            item = {
                'id': root.id,
                'name': root.name,
                'description': root.description,
                'selected': True if root.id in selected_ids else False,
                'children': get_children(root_name, root.id, []),
                'parents': custom_root_parent
            }

            results.append(item)

        return results



    @classmethod
    def get_menu_tree(cls, selected_ids=[], custom_root_parent=[]):

        result = []

        roots = cls.objects.filter(name__regex=r'menu.([^.]*)\.\*', menu_type=True).order_by('order', 'name')

        for root in roots:
            root_name = root.name.replace('.*', '')

            item = {
                'id': root.id,
                'name': root.name,
                'description': root.description,
                'selected': True if root.id in selected_ids else False,
                'children': [],
                'parents': custom_root_parent
            }

            children_1st_level = cls.objects.filter(name__regex=r'{}.([^*]\w*\.\*|\w[^.]*$)'.format(root_name), menu_type=True).order_by('order', 'name')

            for child_1st in children_1st_level:

                children_1st = []
                root_name = child_1st.name.replace('.*', '')
                is_child_root = True if child_1st.name.split('.')[-1] == '*' else False

                if is_child_root:

                    children_2nd_level = cls.objects.filter(name__regex=r'{}.[^*].*'.format(root_name), menu_type=True).order_by('order', 'name')

                    for child_2nd in children_2nd_level:

                        child_2nd_item = {
                            'id': child_2nd.id,
                            'name': child_2nd.name,
                            'description': child_2nd.description,
                            'selected': True if child_2nd.id in selected_ids else False,
                            'children': [],
                            'parents': [root.id, child_1st.id] + custom_root_parent
                        }

                        children_1st.append(child_2nd_item)

                item['children'].append({
                    'id': child_1st.id,
                    'name': child_1st.name,
                    'description': child_1st.description,
                    'selected': True if child_1st.id in selected_ids else False,
                    'children': children_1st,
                    'parents': [root.id] + custom_root_parent
                })

            result.append(item)

        return result


class Role(models.Model):
    description = models.CharField(max_length=80, unique=True)
    permissions = models.ManyToManyField(UserResource, through="switchblade_users.RolePermission")
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('description',)

    def __str__(self):
        return self.description

    def get_delete_url(self):
        return reverse('users-role-delete', kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('users-role-update', kwargs={'pk': self.pk})

    def get_absolute_url(self):
        return reverse('users-role-detail', kwargs={'pk': self.pk})


class RolePermission(models.Model):
    role = models.ForeignKey(Role, on_delete=models.CASCADE)
    resource = models.ForeignKey(UserResource, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.role} - {self.resource}'

    class Meta:
        ordering = ('role', 'resource')


class User(AbstractBaseUser, PermissionsMixin):

    first_name = models.CharField(verbose_name=_('First name'), max_length=80)
    last_name = models.CharField(verbose_name=_('Last name'), max_length=80)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=128)

    last_login = models.DateTimeField(verbose_name=_('Last login'), blank=True, null=True)
    creation_date = models.DateTimeField(verbose_name=_('Creation date'), auto_now_add=True)

    roles = models.ManyToManyField(Role, verbose_name=_('Roles'), blank=True)
    individual_permissions = models.ManyToManyField(UserResource, verbose_name=_('Individual Permissions'), blank=True)

    is_active = models.BooleanField(verbose_name=_('Active'), default=True)
    is_staff = models.BooleanField(verbose_name=_('Staff'), default=False)
    is_admin = models.BooleanField(verbose_name=_('Admin'), default=False)

    avatar = models.ImageField(upload_to="avatars/", blank=True, null=True)

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = UserManager()

    class Meta:
        verbose_name = _("User")
        verbose_name_plural = _("Users")
        ordering = ('first_name', 'last_name')

    def __str__(self):
        return self.get_full_name()

    @classmethod
    def _filter_by_str(cls, q, first_match_id=True, raise_when_not_found=True):

        qs = cls.objects.filter()
        qs = qs.annotate(full_name=Concat('first_name', Value(' '), 'last_name')).filter(full_name__unaccent__icontains=q)

        if first_match_id:
            if qs.exists():
                return qs.first().id
            elif raise_when_not_found:
                raise ValueError(f'User {q} not found.')
            return None

        return qs

    @property
    def is_superuser(self):
        return self.is_admin

    def get_full_name(self):
        return '{} {}'.format(self.first_name, self.last_name)

    def get_short_name(self):
        return self.first_name

    def get_avatar_url(self):
        if self.avatar:
            return self.avatar.url
        return static('switchblade_dashboard/img/default_user.png')

    def has_perm(self, perm, obj=None):
        """
        Does the user have a specific permission?
        """
        if self.is_admin:
            return True
        allowed_resources = self.get_allowed_resources
        if perm in allowed_resources:
            return True
        return False

    def get_all_permissions(self, obj=None):

        return self.get_allowed_resources

    def get_delete_url(self):
        return reverse('users-delete', kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('users-update', kwargs={'pk': self.pk})

    def get_absolute_url(self):
        return reverse('users-detail', kwargs={'pk': self.pk})

    @cached_property
    def get_allowed_resources(self):

        roles_list = list(RolePermission.objects.select_related('role', 'resource').filter(role__pk__in=self.roles.all().values_list('id', flat=True),
                                                        role__active=True).values_list('resource__name', flat=True))

        individual_list = list(self.individual_permissions.all().values_list('name', flat=True))

        return list(set(roles_list + individual_list))

    @classmethod
    def change_password(cls, request, ids):

        from .views import UserChangePassword

        return UserChangePassword().get(request, ids)

code/switchblade_users/templates/users/change_password.html
{% extends "switchblade_dashboard/base.html" %}
{% load dashboard_tag %}
{% load i18n static %}

{% load crispy_forms_tags %}

{% block content_main %}
    <form method="POST" action="{% url 'users-change-password' %}" >
    <div class="box box-default" id="app">
        <div class="box-header with-border">
            <h3 class="box-title"><span>{% trans "Change password" %}</span></h3>
        </div>


        <div class="box-body">

            <div class="callout callout-info">
                <h4>{% trans "Changing password for" %}:</h4>

                <ul>
                    {% for user in user_list %}
                        <li>{{ user }}</li>
                    {% endfor %}
                </ul>

            </div>

            <div class="form-horizontal">
                {% crispy form helper %}

                <input type="hidden" name="ids" value="{{ ids }}">

            </div>
        </div>

        <div class="box-footer">
            <a href="javascript:history.back();" class="btn btn-default"><i class="fa fa-arrow-left"></i>&nbsp;{% trans "Back" %}</a>
            <div class="btn-group pull-right">
                <input type="submit" value="{% trans 'Change password' %}" class="btn btn-success">
            </div>
        </div>
    </div>
    </form>
{% endblock content_main %}

{% block extraHead %}

{% endblock extraHead %}

{% block extraJS %}

{% endblock extraJS %}

{% block title %}
    {% trans "Change password" %}
{% endblock %}

{% block content_title %}
    {% trans "Set new password" %}
{% endblock %}

code/switchblade_users/templates/users/index.html
{% extends "switchblade_dashboard/base.html" %}
{% load i18n %}

{% block title %}
    {% trans "Users" %}
{% endblock %}

{% block content_title %}
    {% trans "Users" %}
{% endblock %}

{% block content_main %}
{% endblock %}


{% block extraJS %}
{% endblock extraJS %}

code/switchblade_users/templates/users/roles.html
{% extends "switchblade_dashboard/base.html" %}
{% load dashboard_tag %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block extraHead %}
    <link rel="stylesheet" href="{% static 'switchblade_users/css/tree.css' %}">
{% endblock %}

{% block title %}
    {% trans "Roles" %}
{% endblock %}

{% block content_title %}
    {% trans "Roles" %}
{% endblock %}

{% block content_main %}
    <form method="POST" action="" enctype="multipart/form-data" id="selected_data_form">
        <div class="box box-default">
            <div class="box-header with-border">
                <h3 class="box-title">{{ description }}</h3>
            </div>
            <div class="box-body">
                <div class="form-horizontal">
                    {% crispy role_form helper %}
                </div>
            </div>
        </div>
        <div class="box box-default">
            <div class="box-header with-border">
                <h3 class="box-title">{% trans "Available resources" %}</h3>
            </div>
            <div class="box-body">
                <div class="row">
                    <div id="resources_tree" class="col-md-6 pad">
                        <twig :nodes="treeData"
                              :id="0.1"
                              :description="'Resources'"
                              :name="'*'"
                              :depth="0"
                              :selected="true">
                        </twig>
                    </div>
                    <div id="menu_tree" class="col-md-6 pad">
                        <twig :nodes="treeData"
                              :id="0.2"
                              :description="'Menu'"
                              :name="'menu.*'"
                              :depth="0"
                              :selected="true">
                        </twig>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <a href="javascript:history.back();" class="btn btn-default">{% trans "Back" %}</a>
                <div class="btn-group pull-right">
                    <input type="hidden" name="id" value="{{ id }}">
                    {% csrf_token %}
                    <input type="hidden" name="selected_data" value="" id="selected_data">
                    <button type="submit" class="btn bg-green">{% trans "Save" %}</button>
                </div>
            </div>
        </div>
    </form>

    <script type="text/x-template" id="twig">
        <div>
            <div @change="on_change()">
                <div :style="indent">
                    <label class="container">
                        <span> [[ description ]] </span>
                        <span class="checkbox-description">([[ name ]])</span>
                        <input :id="id" type="checkbox" :checked="selected">
                        <span class="checkmark"></span>
                    </label>
                </div>
            </div>
            <twig v-for="node in nodes"
                  :key="node.id"
                  :nodes="node.children"
                  :id="node.id"
                  :name="node.name"
                  :parents="node.parents"
                  :description="node.description"
                  :selected="node.selected"
                  :depth="depth + 1">
            </twig>
        </div>
    </script>
{% endblock content_main %}

{% block extraJS %}
    <script src="{% static 'switchblade_users/vue_libs/tree.js' %}"></script>
    <script>
        $(function initiate_tree_checkbox_view() {
            menu_tree.treeData = {{ menu_tree|safe }};
            resources_tree.treeData = {{ resources_tree|safe }};
            selectedData = {{ selected_data|safe }};
        });
    </script>
{% endblock extraJS %}

code/switchblade_users/templates/users/update_avatar.html
{% extends "switchblade_dashboard/base.html" %}
{% load dashboard_tag %}
{% load i18n static %}

{% load crispy_forms_tags %}

{% block content_main %}
    <div class="box box-default" id="app">
        <div class="box-header with-border">
            <h3 class="box-title"><span>{% trans "Please enter your photo." %}</span></h3>
        </div>
        <div class="box-body">


            <div class="row">
                     <div class="control-label col-lg-4 col-lg-offset-2">
                        <label id="label_browse" for="browse">{% trans "Actual Image" %}:</label>
                        <div class="img__wrap">
                                {% if avatar_url %}
                                <img id="avatar_user" class="img-circle img__img" width="350" src="{{ avatar_url }}"
                                     alt="your image"/>
                                {% else %}
                                <img id="avatar_user" class="img-circle img__img" width="350" src="{% static 'switchblade_dashboard/img/default_user.png' %}"
                                     alt="your image"/>
                                {% endif %}
                                    <div class="img__description_layer">
                                        <h3 class="img__description">{% trans "Upload Image" %}</h3>
                                        <div class="img__description" style="margin-top: 16px; margin-left: 5px;"> ({% trans "Max upload file size: 500KB" %})</div>
                                    </div>
                                    <input id="browse" type="file" @change="upload($event)" style="display:none">
                        </div>
                    </div>

                    <div class="control-label col-lg-4 col-lg-offset-2">
                        <label id="label_browse" for="browse">{% trans "New Image" %}:</label>
                        <clipper-fixed
                                class="my-clipper"
                                ref="clipper"
                                :src="imgURL"
                                :round="true"
                                preview="fixed-preview" width="100" >
                                <div class="placeholder" slot="placeholder">{% trans "No image" %}</div>
                        </clipper-fixed>
                    </div>

        </div>
        <div class="box-footer">
            <a href="javascript:history.back();" class="btn btn-default"><i class="fa fa-arrow-left"></i>&nbsp;{% trans "Back" %}</a>
            <div class="btn-group pull-right">
                <input type="submit" @click="saveImage()" value="{% trans 'Save' %}" class="btn btn-success">
            </div>
        </div>
    </div>
    </div>
{% endblock content_main %}

{% block extraHead %}

    <link rel="stylesheet" href="{% static 'switchblade_dashboard/libs/vuejs-clipper/dist/vuejs-clipper.css' %}">
    <link rel="stylesheet" href="{% static 'switchblade_users/css/avatar.css' %}">
{% endblock extraHead %}

{% block extraJS %}
    <script src="{% static 'switchblade_dashboard/libs/vuejs-clipper/dist/vuejs-clipper.umd.min.js' %}"></script>
    <script src="{% static 'switchblade_users/vue_libs/avatar.js' %}"></script>
    <script src="{% static 'switchblade_users/js/avatar.js' %}"></script>
    <script>
        app.csrf_token = '{{ csrf_token }}';
    </script>

{% endblock extraJS %}

{% block title %}
    {% trans "Update Avatar" %}
{% endblock %}

{% block content_title %}
<span>{% trans "Update Avatar" %}</span>
{% endblock %}

code/switchblade_users/templates/users/user_autocomplete.html
{% load i18n %}
{% load thumbnail %}

<span class="block person" data-value="{{ choice.pk }}">
    <img src="{% thumbnail choice.profile_image.url 50x50 crop %}" />

    <a href="{{ choice.get_absolute_url }}">
        {{ choice.first_name }} {{ choice.last_name }}
    </a>

    <a href="{% url 'admin:persons_person_change' choice.pk %}">
        {% trans 'Edit person' %}
    </a>

    {% if choice.company %}
    <a href="{{ choice.get_absolute_url }}">
        {{ choice.company }}
    </a>
    {% endif %}
</span>

code/switchblade_users/templates/users/user_profile_change.html
{% extends "switchblade_dashboard/base.html" %}
{% load dashboard_tag %}
{% load i18n static %}
{% load crispy_forms_tags %}

{% block title %}
    {% trans "User Profile" %}
{% endblock %}

{% block content_title %}
    {% trans "Change Profile" %}
{% endblock %}

{% block content_main %}
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    <div class="box box-default">
        <div class="box-header with-border">
            <h3 class="box-title"><span>{% trans "Please update your personal info" %}</span></h3>
        </div>
        <div class="box-body">
            <div class="form-horizontal">
                <div class="form-group">
                    <label class="control-label col-lg-2 requiredField">
                        {{ form.first_name.label }}<span class="asteriskField">*</span>
                    </label>
                    <div class="controls col-lg-10">
                        {{ form.first_name }}
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-lg-2 requiredField">
                        {{ form.last_name.label }}<span class="asteriskField">*</span>
                    </label>
                    <div class="controls col-lg-10">
                        {{ form.last_name }}
                    </div>
                </div>
            </div>
        </div>
        <div class="box-footer">
            <a href="javascript:history.back();" class="btn btn-default"><i class="fa fa-arrow-left"></i> {% trans "Back" %}</a>
            <div class="btn-group pull-right">
                <input type="submit" value="{% trans 'Change my profile' %}" class="btn btn-success">
            </div>
        </div>
    </div>
</form>
{% endblock content_main %}